//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnyDo.ModelData.Logic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefa
    {
        public int TarefaID { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public Nullable<System.DateTime> DataConclusao { get; set; }
        public bool Concluida { get; set; }
        public int UsuarioID { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
